spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.56.10:3306/joybuy_pms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  redis:
    host: 192.168.56.10
    port: 6379
  cache:
    type: redis




#  resources:
#    static-locations: classpath:templates/,classpath:static/

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

server:
  port: 13000
#logging:
#  level:
#    com.thedustybox.joybuy: debug

logging:
  level:
    com.thedustybox.joybuy: debug
#    com.alibaba.nacos.client.naming: WARN
#    com.alibaba.nacos.client.config.impl: WARN


